Front-end Updated
mattlawnz/gomud-client pull request #10
Opened 2023-12-15 04:44 UTC by Timon0219

General Layout updated

2023-12-15 22:56 UTC, msamad requested changes
I've created a PR https://github.com/mattlawnz/gomud-client/pull/11 which has some fixes for using the config correctly and enables the eslint back on. Have fixed small issues that it was reporting as well.
Merge the PR first please, then there are some initial comments that needs to be addressed. Once those are addressed in this PR, then I can do a detailed round.

2023-12-15 22:56 UTC, msamad commented on src/auth.ts
> +      const response = await fetch(`https://mud.mlmc.nz/api/signup`, {
should not hardcode backend like this, should be injected based on where it is running and for what it's built for

2023-12-15 22:56 UTC, msamad commented on src/pages/public/login/LoginPage.tsx
> +        backgroundImage: 'url(/assets/images/splash.png)',
images are loading in the dev mode but does not work when serving the build.

2023-12-15 22:56 UTC, msamad commented on src/components/Room.tsx
> +            position: 'relative',
The styling is all over the place, I'd prefer it to be properly created with theme and would like use of style classes instead of everything explicitly mentioned for each item. There should really be some consistency in using the styles. 
Just leaving one comment here, will not put it on all the others but it applies to all.

2023-12-16 10:19 UTC, Timon0219 commented on .eslintrc
> -{
Okay, I will remove them. Sometimes it bothered me so I removed them.

2023-12-16 10:24 UTC, Timon0219 commented on src/pages/public/login/LoginPage.tsx
> +        backgroundImage: 'url(/assets/images/splash.png)',
In my end, I mean in the local side, the image was not loading so I've replaced them to work on local. Anyway, I'll solve this issue and will create PR with updated url

2023-12-16 20:28 UTC, msamad commented on .eslintrc
> -{
It is there to make sure that there is consistency in code. Think of it as someone nudging you to write good clean code

2023-12-20 06:06 UTC, merged